<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\index.html" Link="wwwroot\index.html" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\styles\**\*" Link="wwwroot\styles\%(RecursiveDir)%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\scripts\**\*" Link="wwwroot\scripts\%(RecursiveDir)%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\frontend\img\**\*" Link="wwwroot\frontend\img\%(RecursiveDir)%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\frontend\ilustraciones\**\*" Link="wwwroot\frontend\ilustraciones\%(RecursiveDir)%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\frontend\CV\**\*" Link="wwwroot\frontend\CV\%(RecursiveDir)%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
